fix(component PluginButton): Usage of getUI to prevent error TS2604: JSX element type '<element-name>' does not have any construct or call signatures.